services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./PROJECT.Data/vault/file:/vault/file:rw
      - ./PROJECT.Data/vault/data:/vault/data:rw
      - ./PROJECT.Data/vault/config:/vault/config:rw
    cap_add:
      - IPC_LOCK
    command: "server"
    